# Generated by Django 2.2.6 on 2019-11-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, verbose_name='Описание тега')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки(заполняет админ)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='able', to='tagapp.Stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Умение user',
                'verbose_name_plural': 'Умения user',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanting', to='tagapp.Stack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desires', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
