# Generated by Django 2.2.6 on 2019-11-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.TextField(blank=True, max_length=128, verbose_name='Краткое описание'),
        ),
    ]
